import type { ParsedUrlQuery } from 'node:querystring'

import { type  Block,type ExtendedRecordMap  } from 'notion-types'

export * from 'notion-types'

export type NavigationStyle = 'default' | 'custom'

export interface PageError {
  message?: string
  statusCode: number
}

export interface PageProps {
  site?: Site
  recordMap?: ExtendedRecordMap
  pageId?: string
  error?: any
  siteMap?: SiteMap
  isMobile?: boolean
  homeRecordMaps?: { [pageId: string]: ExtendedRecordMap }
  isPrivate?: boolean
  topLevelPageInfo?: PageInfo | null
  showTOC?: boolean
  setBackgroundAsset?: (asset: HTMLImageElement | HTMLVideoElement | string | null) => void
  isHeroPaused?: boolean
  setIsHeroPaused?: (isPaused: boolean) => void
  heroStream?: MediaStream | null
  setHeroStream?: (stream: MediaStream | null) => void
  hideCoverImage?: boolean
  parentSlug?: string
}

export interface Params extends ParsedUrlQuery {
  pageId: string
}

export type Site = {
  domain: string
  name: string

  rootNotionPageId: string | null
  rootNotionSpaceId?: string | null

  // settings
  html?: string
  fontFamily?: string
  darkMode?: boolean
  previewImages?: boolean

  // opengraph metadata
  description?: string
  image?: string

  // Incremental Static Regeneration (ISR) configuration
  isr?: {
    revalidate: number
  }
}

/**
 * Represents the essential properties of a page, derived from the Notion DB.
 * This is a flat structure, easy to store in a map.
 */
export interface PageInfo {
  // From Notion DB
  title: string
  pageId: string
  type: 'Post' | 'Category' | 'Home' | 'Database' | 'Unknown'
  slug: string
  parentPageId: string | null;
  parentDbId?: string | null;
  childrenPageIds: string[];
  language: string | null;
  public: boolean | null
  useOriginalCoverImage: boolean | null
  description: string | null
  date: string | null
  coverImage?: string | null
  coverImageBlock?: Block | null // Add block for mapImageUrl
  tags?: string[] // Tags from Notion multi-select property
  authors?: string[] // Authors from Notion multi-select property
  breadcrumb?: string[] // Breadcrumb titles from root to current page

  // Generated by our code
  parent?: PageInfo
  children: PageInfo[]
  canonicalPageUrl?: string
}

export interface LocaleTagGraphData {
  tagCounts: Record<string, number>
  tagRelationships: Record<string, string[]>
  tagPages: Record<string, string[]>
  totalPosts: number
  lastUpdated: number
}

export interface TagGraphData {
  locales: Record<string, LocaleTagGraphData>
  totalPosts: number
  lastUpdated: number
}

/**
 * The main data structure holding all site information after being processed.
 */
export interface DatabaseInfo {
  id: string
  name: string
  slug: string
  language: string | null
  coverImage?: string | null
}

export interface SiteMap {
  site: Site
  pageInfoMap: Record<string, PageInfo>
  navigationTree: PageInfo[]
  canonicalPageMap: CanonicalPageMap
  tagGraphData?: TagGraphData
  databaseInfoMap?: Record<string, DatabaseInfo>
  lastUpdated: number
}

export interface CanonicalPageMap {
  [canonicalPageId: string]: string
}

export interface PageUrlOverridesMap {
  // maps from a URL path to the notion page id the page should be resolved to
  // (this overrides the built-in URL path generation for these pages)
  [pagePath:string]: string
}

export interface BreadcrumbItem {
  title: string;
  pageId?: string;
  pageInfo?: PageInfo;
  href?: string;
  icon?: React.ReactNode;
}

export interface PageUrlOverridesInverseMap {
  // maps from a notion page id to the URL path the page should be resolved to
  // (this overrides the built-in URL path generation for these pages)
  [pageId: string]: string
}